PHRASE (1,  DOT,        ".",                       46)
PHRASE (1,  ZPT,        ",",                       44)
PHRASE (1,  DEFRET,     "Козырная",               -9895)
PHRASE (1,  ASSNSTART,  "Этим",                   -2411)
PHRASE (1,  ASSNIS,     "был",                    -1469)
PHRASE (1,  KAVYCHKA,   "\"",                      34)
PHRASE (2,  IDX,        "( автору",               -6199)
PHRASE (2,  IDXEND,     "лет )",                  -1580)
PHRASE (2,  NEG,        "Нифига не",              -5885)
PHRASE (2,  DEFNAME,    "называется .",           -15876)
PHRASE (2,  IFSTART,    "Кто прочитал",           -11046)
PHRASE (2,  IFELSE,     "Ставь лайк",             -6358)
PHRASE (2,  RAZ,        "раз .",                  -1399)
PHRASE (3,  IFTHEN,     "тот сдохнет .",          -9255)
PHRASE (3,  WHILESTART, "В дверь постучали",      -16792)
PHRASE (3,  WHILEEND,   "Дверь отвалилась .",     -19211)
PHRASE (3,  RETEND,     ", господа .",            -6649)
PHRASE (4,  DEFPARAM,   "Правила очень просты :", -17135)
PHRASE (4,  INIT,       "Купил мужик шляпу .",    -11213)
PHRASE (4,  DECLEND,    "\" - подумал Штирлиц",   -14449)
PHRASE (5,  ANEKNAME,   "А бармен им говорит :",  -13541)
PHRASE (5,  TOCONST,    "У Штирлица "
                        "отвалилась жопа .",      -27036)
PHRASE (6,  END,        "А она ему как раз .",    -5894)
PHRASE (8,  IFEND,      "и можешь считать , "
                        "что не читал .",         -20283)
PHRASE (8,  ANEK,       "Анекдот : Заходят "
                        "как - то в бар",         -18949)
PHRASE (11, DEFSTART,   "Господа , а не "
                        "сыграть ли нам "
                        "в новую игру .",         -25290)
